config/routes.rb
Rails.application.routes.draw do
  root 'welcomes#index'
  get 'users/index'

  get 'users/show'

  get 'users/new'

  get 'users/edit'

 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def render_error(model)
    render json: { errors: model.errors.full_messages.join(',') }, status: 422
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def edit
  end
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
  def index 
  end
 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UserAjax</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>View Users</h1>
<hr />
<div class="row">
  <div class="col s12 m6">
    <ul class="game-item">
    
        
      
    </ul>
  </div>
  <!-- <div class="row" id="character-list">
    <h3 id="game">Users Information</h2>
    <ul id="characters">
    </ul>
  </div> -->
</div>

app/views/users/new.html.erb
<form>
  <p>First Name</p>
  <input type='text' id='first_name'/>
  <br />
  <p>Last Name</p>
  <input type='text' id='last_name'/>
  <br />
  <p>Phone Number</p>
  <input type='text' id='phone_number'/>
  <br/>
  <button id="button" class="users btn">Create New User</button>
  <%= link_to 'Back', root_path, class: "users btn" %>
</form>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/welcomes/index.html.erb
<h1 class="center">Welcome to our App!</h1>

<div class="center">
  <button class="users btn">View Users</button>
  <%= link_to 'create users', users_new_path, class: "btn" %>
</div>

<hr />
<div class="row">
  <div class="col s12 m6">
    <ul class="game-item">
    </ul>
  </div>
</div>